name = "link-me"
main = "src/index.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
APP_NAME = "link-me"

[[kv_namespaces]]
binding = "CONTACTS_KV"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"
